//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/PSEmulator/PSLauncher/master/PSLauncher/mainfes" +
            "t.json")]
        public string Manifest {
            get {
                return ((string)(this["Manifest"]));
            }
            set {
                this["Manifest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/PSEmulator/PSLauncher/master/PSLauncher/mainfes" +
            "t.json")]
        public string DefaultManifest {
            get {
                return ((string)(this["DefaultManifest"]));
            }
            set {
                this["DefaultManifest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.psemulator.org/forums")]
        public string AccountURL {
            get {
                return ((string)(this["AccountURL"]));
            }
            set {
                this["AccountURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104.236.204.206")]
        public string UpdateServerIP {
            get {
                return ((string)(this["UpdateServerIP"]));
            }
            set {
                this["UpdateServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("launcher")]
        public string UpdateServerUser {
            get {
                return ((string)(this["UpdateServerUser"]));
            }
            set {
                this["UpdateServerUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("psemu")]
        public string UpdateServerPassword {
            get {
                return ((string)(this["UpdateServerPassword"]));
            }
            set {
                this["UpdateServerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlanetsideInstallDir {
            get {
                return ((string)(this["PlanetsideInstallDir"]));
            }
            set {
                this["PlanetsideInstallDir"] = value;
            }
        }
    }
}
